name: CI
on:
  push

jobs:
  tests:
    name: pytest on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Upgrade pip
        shell: bash
        run: python -m pip install --upgrade pip

      - name: Install deps (if any)
        if: hashFiles('requirements.txt') != ''
        shell: bash
        run: python -m pip install -r requirements.txt

      - name: Install pytest
        shell: bash
        run: python -m pip install pytest

      - name: Show workspace (debug)
        shell: bash
        run: |
          pwd
          ls -la
          echo "---- tests dir (if exists) ----"
          ls -la tests || true
          echo "---- test files ----"
          find . -maxdepth 3 -type f -name "test_*.py" -print || true

      - name: Run tests
        shell: bash
        run: |
          if [ -d tests ]; then
            pytest -q tests
          else
            pytest -q
          fi
