name: CI
on:
  push

jobs:
  tests:
    name: unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show workspace (brief)
        shell: bash
        run: |
          python -V
          pwd
          ls -la
          echo "---- tests ----"
          ls -la tests || true
          echo "---- geometric_lib ----"
          ls -la geometric_lib || true

      - name: Run unittest discovery
        shell: bash
        run: python -m unittest discover -s tests -p "test_*.py" -v
