name: CI
on:
  push

jobs:
  tests:
    name: unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
            submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # можно 3.10/3.12, не критично

      - name: Show workspace (debug)
        run: |
          pwd
          ls -la
          echo "---- tests dir ----"
          ls -la tests || true

      # зависимостей нет — ничего не ставим

      - name: Run unittest discovery
        run: python -m unittest discover -s tests -p "test_*.py" -v
